name: Continuous Integration

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: pgvector/pgvector:pg15
        env:
          POSTGRES_PASSWORD: reckie_password
          POSTGRES_USER: reckie
          POSTGRES_DB: reckie_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        uv venv
        source .venv/bin/activate
        uv pip install -e ".[dev]"

    - name: Install Playwright browsers
      run: |
        source .venv/bin/activate
        playwright install --with-deps

    - name: Run unit tests
      run: |
        source .venv/bin/activate
        pytest tests/unit/ -v

    - name: Run integration tests
      run: |
        source .venv/bin/activate
        pytest tests/integration/ -v
      env:
        DATABASE_URL: postgresql://reckie:reckie_password@localhost:5432/reckie_db

    - name: Start application for E2E tests
      run: |
        source .venv/bin/activate
        uvicorn app.main:app --host 0.0.0.0 --port 8000 &
        sleep 5
      env:
        DATABASE_URL: postgresql://reckie:reckie_password@localhost:5432/reckie_db

    - name: Run E2E tests
      run: |
        source .venv/bin/activate
        pytest tests/e2e/ -v

    - name: Generate coverage report
      run: |
        source .venv/bin/activate
        coverage run -m pytest tests/
        coverage xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml